---
- name: install mod_php
  apt: name=libapache2-mod-php state=latest
  notify: reload apache

- name: install php.ini
  template: src=php.ini.j2 dest=/etc/php/7.0/apache2/php.ini owner=root group=root mode=0644
  notify: reload apache

- name: install php packages
  apt: name=php-{{ item }} state=latest
  with_items: "{{ php_packages }}"
  notify: reload apache

- name: install pear
  apt: name=php-pear state=latest

- name: install pear packages
  pear: name={{ item }} state=present
  with_items: "{{ php_pear_packages }}"

- name: install php cli
  apt: name=php-cli state=latest

- include: vagrant.yml
  when: is_vagrant is defined and is_vagrant
